name = "turkey-coin-hub"
compatibility_date = "2026-02-24"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "turkey-coin"
database_id = "6fdfc623-409b-4dbd-ba77-3331187f1771"
preview_database_id = "6fdfc623-409b-4dbd-ba77-3331187f1771"
